// Code generated by protoc-gen-go. DO NOT EDIT.
// source: showing/proto/showing.proto

package showing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateShowingRequest struct {
	MovieID              string   `protobuf:"bytes,1,opt,name=movieID,proto3" json:"movieID,omitempty"`
	RoomName             string   `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShowingRequest) Reset()         { *m = CreateShowingRequest{} }
func (m *CreateShowingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateShowingRequest) ProtoMessage()    {}
func (*CreateShowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{0}
}

func (m *CreateShowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShowingRequest.Unmarshal(m, b)
}
func (m *CreateShowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShowingRequest.Marshal(b, m, deterministic)
}
func (m *CreateShowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShowingRequest.Merge(m, src)
}
func (m *CreateShowingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateShowingRequest.Size(m)
}
func (m *CreateShowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShowingRequest proto.InternalMessageInfo

func (m *CreateShowingRequest) GetMovieID() string {
	if m != nil {
		return m.MovieID
	}
	return ""
}

func (m *CreateShowingRequest) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

type CreateShowingResponse struct {
	Message              string         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NewShowing           *ShowingStruct `protobuf:"bytes,2,opt,name=newShowing,proto3" json:"newShowing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateShowingResponse) Reset()         { *m = CreateShowingResponse{} }
func (m *CreateShowingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateShowingResponse) ProtoMessage()    {}
func (*CreateShowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{1}
}

func (m *CreateShowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShowingResponse.Unmarshal(m, b)
}
func (m *CreateShowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShowingResponse.Marshal(b, m, deterministic)
}
func (m *CreateShowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShowingResponse.Merge(m, src)
}
func (m *CreateShowingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateShowingResponse.Size(m)
}
func (m *CreateShowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShowingResponse proto.InternalMessageInfo

func (m *CreateShowingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateShowingResponse) GetNewShowing() *ShowingStruct {
	if m != nil {
		return m.NewShowing
	}
	return nil
}

type ReadShowingRequest struct {
	ShowingID            string   `protobuf:"bytes,1,opt,name=showingID,proto3" json:"showingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadShowingRequest) Reset()         { *m = ReadShowingRequest{} }
func (m *ReadShowingRequest) String() string { return proto.CompactTextString(m) }
func (*ReadShowingRequest) ProtoMessage()    {}
func (*ReadShowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{2}
}

func (m *ReadShowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadShowingRequest.Unmarshal(m, b)
}
func (m *ReadShowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadShowingRequest.Marshal(b, m, deterministic)
}
func (m *ReadShowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadShowingRequest.Merge(m, src)
}
func (m *ReadShowingRequest) XXX_Size() int {
	return xxx_messageInfo_ReadShowingRequest.Size(m)
}
func (m *ReadShowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadShowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadShowingRequest proto.InternalMessageInfo

func (m *ReadShowingRequest) GetShowingID() string {
	if m != nil {
		return m.ShowingID
	}
	return ""
}

type ReadShowingResponse struct {
	Message              string         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Response             *ShowingStruct `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReadShowingResponse) Reset()         { *m = ReadShowingResponse{} }
func (m *ReadShowingResponse) String() string { return proto.CompactTextString(m) }
func (*ReadShowingResponse) ProtoMessage()    {}
func (*ReadShowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{3}
}

func (m *ReadShowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadShowingResponse.Unmarshal(m, b)
}
func (m *ReadShowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadShowingResponse.Marshal(b, m, deterministic)
}
func (m *ReadShowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadShowingResponse.Merge(m, src)
}
func (m *ReadShowingResponse) XXX_Size() int {
	return xxx_messageInfo_ReadShowingResponse.Size(m)
}
func (m *ReadShowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadShowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadShowingResponse proto.InternalMessageInfo

func (m *ReadShowingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReadShowingResponse) GetResponse() *ShowingStruct {
	if m != nil {
		return m.Response
	}
	return nil
}

type UpdateShowingRequest struct {
	ShowingID            string         `protobuf:"bytes,1,opt,name=showingID,proto3" json:"showingID,omitempty"`
	UpdatedShowing       *ShowingStruct `protobuf:"bytes,2,opt,name=updatedShowing,proto3" json:"updatedShowing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateShowingRequest) Reset()         { *m = UpdateShowingRequest{} }
func (m *UpdateShowingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateShowingRequest) ProtoMessage()    {}
func (*UpdateShowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{4}
}

func (m *UpdateShowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateShowingRequest.Unmarshal(m, b)
}
func (m *UpdateShowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateShowingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateShowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateShowingRequest.Merge(m, src)
}
func (m *UpdateShowingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateShowingRequest.Size(m)
}
func (m *UpdateShowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateShowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateShowingRequest proto.InternalMessageInfo

func (m *UpdateShowingRequest) GetShowingID() string {
	if m != nil {
		return m.ShowingID
	}
	return ""
}

func (m *UpdateShowingRequest) GetUpdatedShowing() *ShowingStruct {
	if m != nil {
		return m.UpdatedShowing
	}
	return nil
}

type UpdateShowingResponse struct {
	UpdatedShowing       *ShowingStruct `protobuf:"bytes,1,opt,name=updatedShowing,proto3" json:"updatedShowing,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateShowingResponse) Reset()         { *m = UpdateShowingResponse{} }
func (m *UpdateShowingResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateShowingResponse) ProtoMessage()    {}
func (*UpdateShowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{5}
}

func (m *UpdateShowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateShowingResponse.Unmarshal(m, b)
}
func (m *UpdateShowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateShowingResponse.Marshal(b, m, deterministic)
}
func (m *UpdateShowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateShowingResponse.Merge(m, src)
}
func (m *UpdateShowingResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateShowingResponse.Size(m)
}
func (m *UpdateShowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateShowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateShowingResponse proto.InternalMessageInfo

func (m *UpdateShowingResponse) GetUpdatedShowing() *ShowingStruct {
	if m != nil {
		return m.UpdatedShowing
	}
	return nil
}

func (m *UpdateShowingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteShowingRequest struct {
	ShowingID            string   `protobuf:"bytes,1,opt,name=showingID,proto3" json:"showingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowingRequest) Reset()         { *m = DeleteShowingRequest{} }
func (m *DeleteShowingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowingRequest) ProtoMessage()    {}
func (*DeleteShowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{6}
}

func (m *DeleteShowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowingRequest.Unmarshal(m, b)
}
func (m *DeleteShowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowingRequest.Merge(m, src)
}
func (m *DeleteShowingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowingRequest.Size(m)
}
func (m *DeleteShowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowingRequest proto.InternalMessageInfo

func (m *DeleteShowingRequest) GetShowingID() string {
	if m != nil {
		return m.ShowingID
	}
	return ""
}

type DeleteShowingResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowingResponse) Reset()         { *m = DeleteShowingResponse{} }
func (m *DeleteShowingResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteShowingResponse) ProtoMessage()    {}
func (*DeleteShowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{7}
}

func (m *DeleteShowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowingResponse.Unmarshal(m, b)
}
func (m *DeleteShowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteShowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowingResponse.Merge(m, src)
}
func (m *DeleteShowingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteShowingResponse.Size(m)
}
func (m *DeleteShowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowingResponse proto.InternalMessageInfo

func (m *DeleteShowingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetAllShowingsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllShowingsRequest) Reset()         { *m = GetAllShowingsRequest{} }
func (m *GetAllShowingsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllShowingsRequest) ProtoMessage()    {}
func (*GetAllShowingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{8}
}

func (m *GetAllShowingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllShowingsRequest.Unmarshal(m, b)
}
func (m *GetAllShowingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllShowingsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllShowingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllShowingsRequest.Merge(m, src)
}
func (m *GetAllShowingsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllShowingsRequest.Size(m)
}
func (m *GetAllShowingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllShowingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllShowingsRequest proto.InternalMessageInfo

type GetAllShowingsResponse struct {
	AllShowings          []*ShowingStruct `protobuf:"bytes,1,rep,name=allShowings,proto3" json:"allShowings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetAllShowingsResponse) Reset()         { *m = GetAllShowingsResponse{} }
func (m *GetAllShowingsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllShowingsResponse) ProtoMessage()    {}
func (*GetAllShowingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{9}
}

func (m *GetAllShowingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllShowingsResponse.Unmarshal(m, b)
}
func (m *GetAllShowingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllShowingsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllShowingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllShowingsResponse.Merge(m, src)
}
func (m *GetAllShowingsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllShowingsResponse.Size(m)
}
func (m *GetAllShowingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllShowingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllShowingsResponse proto.InternalMessageInfo

func (m *GetAllShowingsResponse) GetAllShowings() []*ShowingStruct {
	if m != nil {
		return m.AllShowings
	}
	return nil
}

type ShowingStruct struct {
	ShowingID            string   `protobuf:"bytes,1,opt,name=showingID,proto3" json:"showingID,omitempty"`
	MovieID              string   `protobuf:"bytes,2,opt,name=movieID,proto3" json:"movieID,omitempty"`
	RoomName             string   `protobuf:"bytes,3,opt,name=roomName,proto3" json:"roomName,omitempty"`
	AvailableSeats       int32    `protobuf:"varint,4,opt,name=availableSeats,proto3" json:"availableSeats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowingStruct) Reset()         { *m = ShowingStruct{} }
func (m *ShowingStruct) String() string { return proto.CompactTextString(m) }
func (*ShowingStruct) ProtoMessage()    {}
func (*ShowingStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{10}
}

func (m *ShowingStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowingStruct.Unmarshal(m, b)
}
func (m *ShowingStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowingStruct.Marshal(b, m, deterministic)
}
func (m *ShowingStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowingStruct.Merge(m, src)
}
func (m *ShowingStruct) XXX_Size() int {
	return xxx_messageInfo_ShowingStruct.Size(m)
}
func (m *ShowingStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowingStruct.DiscardUnknown(m)
}

var xxx_messageInfo_ShowingStruct proto.InternalMessageInfo

func (m *ShowingStruct) GetShowingID() string {
	if m != nil {
		return m.ShowingID
	}
	return ""
}

func (m *ShowingStruct) GetMovieID() string {
	if m != nil {
		return m.MovieID
	}
	return ""
}

func (m *ShowingStruct) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *ShowingStruct) GetAvailableSeats() int32 {
	if m != nil {
		return m.AvailableSeats
	}
	return 0
}

type DeleteShowingsForMovieRequest struct {
	MovieID              string   `protobuf:"bytes,1,opt,name=movieID,proto3" json:"movieID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowingsForMovieRequest) Reset()         { *m = DeleteShowingsForMovieRequest{} }
func (m *DeleteShowingsForMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowingsForMovieRequest) ProtoMessage()    {}
func (*DeleteShowingsForMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{11}
}

func (m *DeleteShowingsForMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowingsForMovieRequest.Unmarshal(m, b)
}
func (m *DeleteShowingsForMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowingsForMovieRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShowingsForMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowingsForMovieRequest.Merge(m, src)
}
func (m *DeleteShowingsForMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowingsForMovieRequest.Size(m)
}
func (m *DeleteShowingsForMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowingsForMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowingsForMovieRequest proto.InternalMessageInfo

func (m *DeleteShowingsForMovieRequest) GetMovieID() string {
	if m != nil {
		return m.MovieID
	}
	return ""
}

type DeleteShowingsForMovieResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowingsForMovieResponse) Reset()         { *m = DeleteShowingsForMovieResponse{} }
func (m *DeleteShowingsForMovieResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteShowingsForMovieResponse) ProtoMessage()    {}
func (*DeleteShowingsForMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{12}
}

func (m *DeleteShowingsForMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowingsForMovieResponse.Unmarshal(m, b)
}
func (m *DeleteShowingsForMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowingsForMovieResponse.Marshal(b, m, deterministic)
}
func (m *DeleteShowingsForMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowingsForMovieResponse.Merge(m, src)
}
func (m *DeleteShowingsForMovieResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteShowingsForMovieResponse.Size(m)
}
func (m *DeleteShowingsForMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowingsForMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowingsForMovieResponse proto.InternalMessageInfo

func (m *DeleteShowingsForMovieResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteShowingsForRoomRequest struct {
	RoomName             string   `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowingsForRoomRequest) Reset()         { *m = DeleteShowingsForRoomRequest{} }
func (m *DeleteShowingsForRoomRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowingsForRoomRequest) ProtoMessage()    {}
func (*DeleteShowingsForRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{13}
}

func (m *DeleteShowingsForRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowingsForRoomRequest.Unmarshal(m, b)
}
func (m *DeleteShowingsForRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowingsForRoomRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShowingsForRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowingsForRoomRequest.Merge(m, src)
}
func (m *DeleteShowingsForRoomRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowingsForRoomRequest.Size(m)
}
func (m *DeleteShowingsForRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowingsForRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowingsForRoomRequest proto.InternalMessageInfo

func (m *DeleteShowingsForRoomRequest) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

type DeleteShowingsForRoomResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowingsForRoomResponse) Reset()         { *m = DeleteShowingsForRoomResponse{} }
func (m *DeleteShowingsForRoomResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteShowingsForRoomResponse) ProtoMessage()    {}
func (*DeleteShowingsForRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c331378aff4f342b, []int{14}
}

func (m *DeleteShowingsForRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowingsForRoomResponse.Unmarshal(m, b)
}
func (m *DeleteShowingsForRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowingsForRoomResponse.Marshal(b, m, deterministic)
}
func (m *DeleteShowingsForRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowingsForRoomResponse.Merge(m, src)
}
func (m *DeleteShowingsForRoomResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteShowingsForRoomResponse.Size(m)
}
func (m *DeleteShowingsForRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowingsForRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowingsForRoomResponse proto.InternalMessageInfo

func (m *DeleteShowingsForRoomResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateShowingRequest)(nil), "CreateShowingRequest")
	proto.RegisterType((*CreateShowingResponse)(nil), "CreateShowingResponse")
	proto.RegisterType((*ReadShowingRequest)(nil), "ReadShowingRequest")
	proto.RegisterType((*ReadShowingResponse)(nil), "ReadShowingResponse")
	proto.RegisterType((*UpdateShowingRequest)(nil), "UpdateShowingRequest")
	proto.RegisterType((*UpdateShowingResponse)(nil), "UpdateShowingResponse")
	proto.RegisterType((*DeleteShowingRequest)(nil), "DeleteShowingRequest")
	proto.RegisterType((*DeleteShowingResponse)(nil), "DeleteShowingResponse")
	proto.RegisterType((*GetAllShowingsRequest)(nil), "GetAllShowingsRequest")
	proto.RegisterType((*GetAllShowingsResponse)(nil), "GetAllShowingsResponse")
	proto.RegisterType((*ShowingStruct)(nil), "ShowingStruct")
	proto.RegisterType((*DeleteShowingsForMovieRequest)(nil), "DeleteShowingsForMovieRequest")
	proto.RegisterType((*DeleteShowingsForMovieResponse)(nil), "DeleteShowingsForMovieResponse")
	proto.RegisterType((*DeleteShowingsForRoomRequest)(nil), "DeleteShowingsForRoomRequest")
	proto.RegisterType((*DeleteShowingsForRoomResponse)(nil), "DeleteShowingsForRoomResponse")
}

func init() { proto.RegisterFile("showing/proto/showing.proto", fileDescriptor_c331378aff4f342b) }

var fileDescriptor_c331378aff4f342b = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xb5, 0xd3, 0x42, 0xdb, 0x89, 0x9a, 0xc3, 0x36, 0x76, 0x2d, 0xd3, 0x86, 0x68, 0x0e, 0xa8,
	0xe2, 0x30, 0x85, 0x80, 0x90, 0xc8, 0x09, 0xd4, 0x0a, 0x04, 0x02, 0x0e, 0x8e, 0x90, 0x90, 0x7a,
	0xda, 0x92, 0x55, 0x89, 0xe4, 0x64, 0x83, 0xd7, 0x69, 0x7f, 0x02, 0x07, 0xfe, 0x34, 0xaa, 0xb3,
	0x49, 0xbc, 0xeb, 0x8d, 0x4d, 0x8f, 0xb3, 0x33, 0xf3, 0xe6, 0xc3, 0xef, 0x8d, 0xe1, 0x89, 0xfa,
	0x25, 0xef, 0x26, 0xb3, 0x9b, 0xf3, 0x79, 0x26, 0x73, 0x79, 0xae, 0x2d, 0x2a, 0x2c, 0xfc, 0x02,
	0xdd, 0x8b, 0x4c, 0xf0, 0x5c, 0x8c, 0x96, 0xcf, 0x89, 0xf8, 0xbd, 0x10, 0x2a, 0x67, 0x11, 0xec,
	0x4d, 0xe5, 0xed, 0x44, 0x7c, 0xba, 0x8c, 0xfc, 0xbe, 0x7f, 0x76, 0x90, 0xac, 0x4c, 0x16, 0xc3,
	0x7e, 0x26, 0xe5, 0xf4, 0x1b, 0x9f, 0x8a, 0xa8, 0x55, 0xb8, 0xd6, 0x36, 0x72, 0x08, 0x2c, 0x34,
	0x35, 0x97, 0x33, 0x25, 0x0a, 0x38, 0xa1, 0x14, 0xbf, 0x11, 0x6b, 0xb8, 0xa5, 0xc9, 0x08, 0x60,
	0x26, 0xee, 0x74, 0x7c, 0x01, 0xd8, 0x1e, 0x74, 0x48, 0xdb, 0xa3, 0x3c, 0x5b, 0xfc, 0xcc, 0x93,
	0x52, 0x04, 0x0e, 0x80, 0x25, 0x82, 0x8f, 0xad, 0x76, 0x4f, 0xe0, 0x40, 0xcf, 0xb5, 0x6e, 0x78,
	0xf3, 0x80, 0x57, 0x70, 0x64, 0xe4, 0x34, 0x36, 0xf5, 0x1c, 0xf6, 0x33, 0x1d, 0xb5, 0xa5, 0xa5,
	0xb5, 0x1f, 0x53, 0xe8, 0x7e, 0x9f, 0x8f, 0xab, 0x1b, 0xac, 0x6d, 0x89, 0xbd, 0x81, 0xce, 0xa2,
	0xc8, 0x1a, 0xd7, 0x8f, 0x6e, 0x45, 0xe1, 0x04, 0x02, 0xab, 0x9a, 0x1e, 0xa6, 0x0a, 0xe8, 0xff,
	0x0f, 0x60, 0x79, 0x09, 0x2d, 0x63, 0x09, 0xf8, 0x1a, 0xba, 0x97, 0x22, 0x15, 0x0f, 0x1b, 0x0c,
	0x5f, 0x42, 0x60, 0x65, 0x35, 0x6d, 0x1b, 0x8f, 0x21, 0xf8, 0x28, 0xf2, 0xf7, 0x69, 0xaa, 0x53,
	0x94, 0xae, 0x84, 0x9f, 0x21, 0xb4, 0x1d, 0x1a, 0xec, 0x05, 0xb4, 0xf9, 0xe6, 0x39, 0xf2, 0xfb,
	0x3b, 0x8e, 0x51, 0xcb, 0x21, 0xf8, 0xd7, 0x87, 0x43, 0xc3, 0xdd, 0xf0, 0x81, 0x4a, 0x02, 0x68,
	0x6d, 0x17, 0xc0, 0x8e, 0x29, 0x00, 0xf6, 0x0c, 0x3a, 0xfc, 0x96, 0x4f, 0x52, 0x7e, 0x9d, 0x8a,
	0x91, 0xe0, 0xb9, 0x8a, 0x76, 0xfb, 0xfe, 0xd9, 0xa3, 0xc4, 0x7a, 0xc5, 0xb7, 0x70, 0x6a, 0x6c,
	0x49, 0x7d, 0x90, 0xd9, 0xd7, 0x7b, 0xfc, 0x46, 0xfd, 0xe1, 0x10, 0x7a, 0xdb, 0x52, 0x1b, 0x37,
	0x3d, 0x84, 0x93, 0x4a, 0x6e, 0x22, 0xe5, 0x74, 0x55, 0xb5, 0x3c, 0x9a, 0x6f, 0x69, 0xdb, 0xd5,
	0xf2, 0x32, 0xb7, 0xa9, 0xec, 0xe0, 0xcf, 0x2e, 0xec, 0xad, 0xf8, 0xf6, 0x0e, 0x0e, 0x8d, 0x13,
	0xc1, 0x02, 0x72, 0x1d, 0xa0, 0x38, 0x24, 0xe7, 0x25, 0x41, 0x8f, 0x0d, 0xa1, 0x5d, 0x52, 0x33,
	0x3b, 0xa2, 0xea, 0x3d, 0x88, 0xbb, 0xe4, 0x10, 0x3c, 0x7a, 0xf7, 0xd5, 0x0d, 0xf9, 0xb0, 0x80,
	0x5c, 0xe2, 0x8d, 0x43, 0x72, 0xaa, 0x6c, 0x89, 0x60, 0xac, 0x81, 0x05, 0xe4, 0x52, 0x49, 0x1c,
	0x92, 0x53, 0x06, 0xe8, 0xb1, 0x0b, 0xe8, 0x98, 0xac, 0x66, 0x21, 0x39, 0xf9, 0x1f, 0x1f, 0x93,
	0x9b, 0xfe, 0xe8, 0xb1, 0x2b, 0x08, 0xdd, 0x2c, 0x60, 0x3d, 0xaa, 0x65, 0x56, 0xfc, 0x94, 0xea,
	0xe9, 0x83, 0x1e, 0xfb, 0x61, 0x69, 0x78, 0xf5, 0xa9, 0xd9, 0x29, 0xd5, 0xd1, 0x27, 0xee, 0x51,
	0x2d, 0x43, 0xd0, 0xbb, 0x7e, 0x5c, 0xfc, 0x75, 0x5e, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xfc,
	0x8e, 0x73, 0x12, 0x94, 0x06, 0x00, 0x00,
}
