// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movie/proto/movie.proto

package movie

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadMovieRequest struct {
	MovieID              string   `protobuf:"bytes,1,opt,name=movieID,proto3" json:"movieID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMovieRequest) Reset()         { *m = ReadMovieRequest{} }
func (m *ReadMovieRequest) String() string { return proto.CompactTextString(m) }
func (*ReadMovieRequest) ProtoMessage()    {}
func (*ReadMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71599ad742c5de64, []int{0}
}

func (m *ReadMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMovieRequest.Unmarshal(m, b)
}
func (m *ReadMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMovieRequest.Marshal(b, m, deterministic)
}
func (m *ReadMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMovieRequest.Merge(m, src)
}
func (m *ReadMovieRequest) XXX_Size() int {
	return xxx_messageInfo_ReadMovieRequest.Size(m)
}
func (m *ReadMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMovieRequest proto.InternalMessageInfo

func (m *ReadMovieRequest) GetMovieID() string {
	if m != nil {
		return m.MovieID
	}
	return ""
}

type ReadMovieResponse struct {
	Message              string       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Movie                *MovieStruct `protobuf:"bytes,2,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReadMovieResponse) Reset()         { *m = ReadMovieResponse{} }
func (m *ReadMovieResponse) String() string { return proto.CompactTextString(m) }
func (*ReadMovieResponse) ProtoMessage()    {}
func (*ReadMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71599ad742c5de64, []int{1}
}

func (m *ReadMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMovieResponse.Unmarshal(m, b)
}
func (m *ReadMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMovieResponse.Marshal(b, m, deterministic)
}
func (m *ReadMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMovieResponse.Merge(m, src)
}
func (m *ReadMovieResponse) XXX_Size() int {
	return xxx_messageInfo_ReadMovieResponse.Size(m)
}
func (m *ReadMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMovieResponse proto.InternalMessageInfo

func (m *ReadMovieResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReadMovieResponse) GetMovie() *MovieStruct {
	if m != nil {
		return m.Movie
	}
	return nil
}

type CreateMovieRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fsk                  int32    `protobuf:"varint,2,opt,name=fsk,proto3" json:"fsk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieRequest) Reset()         { *m = CreateMovieRequest{} }
func (m *CreateMovieRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMovieRequest) ProtoMessage()    {}
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71599ad742c5de64, []int{2}
}

func (m *CreateMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieRequest.Unmarshal(m, b)
}
func (m *CreateMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieRequest.Marshal(b, m, deterministic)
}
func (m *CreateMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieRequest.Merge(m, src)
}
func (m *CreateMovieRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMovieRequest.Size(m)
}
func (m *CreateMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieRequest proto.InternalMessageInfo

func (m *CreateMovieRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateMovieRequest) GetFsk() int32 {
	if m != nil {
		return m.Fsk
	}
	return 0
}

type CreateMovieResponse struct {
	Message              string       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NewMovie             *MovieStruct `protobuf:"bytes,2,opt,name=newMovie,proto3" json:"newMovie,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateMovieResponse) Reset()         { *m = CreateMovieResponse{} }
func (m *CreateMovieResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMovieResponse) ProtoMessage()    {}
func (*CreateMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71599ad742c5de64, []int{3}
}

func (m *CreateMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieResponse.Unmarshal(m, b)
}
func (m *CreateMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieResponse.Marshal(b, m, deterministic)
}
func (m *CreateMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieResponse.Merge(m, src)
}
func (m *CreateMovieResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMovieResponse.Size(m)
}
func (m *CreateMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieResponse proto.InternalMessageInfo

func (m *CreateMovieResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateMovieResponse) GetNewMovie() *MovieStruct {
	if m != nil {
		return m.NewMovie
	}
	return nil
}

type DeleteMovieRequest struct {
	MovieID              string   `protobuf:"bytes,1,opt,name=movieID,proto3" json:"movieID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieRequest) Reset()         { *m = DeleteMovieRequest{} }
func (m *DeleteMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieRequest) ProtoMessage()    {}
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71599ad742c5de64, []int{4}
}

func (m *DeleteMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieRequest.Unmarshal(m, b)
}
func (m *DeleteMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieRequest.Merge(m, src)
}
func (m *DeleteMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieRequest.Size(m)
}
func (m *DeleteMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieRequest proto.InternalMessageInfo

func (m *DeleteMovieRequest) GetMovieID() string {
	if m != nil {
		return m.MovieID
	}
	return ""
}

type DeleteMovieResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieResponse) Reset()         { *m = DeleteMovieResponse{} }
func (m *DeleteMovieResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieResponse) ProtoMessage()    {}
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71599ad742c5de64, []int{5}
}

func (m *DeleteMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieResponse.Unmarshal(m, b)
}
func (m *DeleteMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieResponse.Merge(m, src)
}
func (m *DeleteMovieResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieResponse.Size(m)
}
func (m *DeleteMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieResponse proto.InternalMessageInfo

func (m *DeleteMovieResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetAllMoviesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllMoviesRequest) Reset()         { *m = GetAllMoviesRequest{} }
func (m *GetAllMoviesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllMoviesRequest) ProtoMessage()    {}
func (*GetAllMoviesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71599ad742c5de64, []int{6}
}

func (m *GetAllMoviesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllMoviesRequest.Unmarshal(m, b)
}
func (m *GetAllMoviesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllMoviesRequest.Marshal(b, m, deterministic)
}
func (m *GetAllMoviesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllMoviesRequest.Merge(m, src)
}
func (m *GetAllMoviesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllMoviesRequest.Size(m)
}
func (m *GetAllMoviesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllMoviesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllMoviesRequest proto.InternalMessageInfo

type GetAllMoviesResponse struct {
	AllMovies            []*MovieStruct `protobuf:"bytes,1,rep,name=allMovies,proto3" json:"allMovies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetAllMoviesResponse) Reset()         { *m = GetAllMoviesResponse{} }
func (m *GetAllMoviesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllMoviesResponse) ProtoMessage()    {}
func (*GetAllMoviesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71599ad742c5de64, []int{7}
}

func (m *GetAllMoviesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllMoviesResponse.Unmarshal(m, b)
}
func (m *GetAllMoviesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllMoviesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllMoviesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllMoviesResponse.Merge(m, src)
}
func (m *GetAllMoviesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllMoviesResponse.Size(m)
}
func (m *GetAllMoviesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllMoviesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllMoviesResponse proto.InternalMessageInfo

func (m *GetAllMoviesResponse) GetAllMovies() []*MovieStruct {
	if m != nil {
		return m.AllMovies
	}
	return nil
}

type MovieStruct struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fsk                  int32    `protobuf:"varint,3,opt,name=fsk,proto3" json:"fsk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieStruct) Reset()         { *m = MovieStruct{} }
func (m *MovieStruct) String() string { return proto.CompactTextString(m) }
func (*MovieStruct) ProtoMessage()    {}
func (*MovieStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_71599ad742c5de64, []int{8}
}

func (m *MovieStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieStruct.Unmarshal(m, b)
}
func (m *MovieStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieStruct.Marshal(b, m, deterministic)
}
func (m *MovieStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieStruct.Merge(m, src)
}
func (m *MovieStruct) XXX_Size() int {
	return xxx_messageInfo_MovieStruct.Size(m)
}
func (m *MovieStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieStruct.DiscardUnknown(m)
}

var xxx_messageInfo_MovieStruct proto.InternalMessageInfo

func (m *MovieStruct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MovieStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MovieStruct) GetFsk() int32 {
	if m != nil {
		return m.Fsk
	}
	return 0
}

func init() {
	proto.RegisterType((*ReadMovieRequest)(nil), "ReadMovieRequest")
	proto.RegisterType((*ReadMovieResponse)(nil), "ReadMovieResponse")
	proto.RegisterType((*CreateMovieRequest)(nil), "CreateMovieRequest")
	proto.RegisterType((*CreateMovieResponse)(nil), "CreateMovieResponse")
	proto.RegisterType((*DeleteMovieRequest)(nil), "DeleteMovieRequest")
	proto.RegisterType((*DeleteMovieResponse)(nil), "DeleteMovieResponse")
	proto.RegisterType((*GetAllMoviesRequest)(nil), "GetAllMoviesRequest")
	proto.RegisterType((*GetAllMoviesResponse)(nil), "GetAllMoviesResponse")
	proto.RegisterType((*MovieStruct)(nil), "MovieStruct")
}

func init() { proto.RegisterFile("movie/proto/movie.proto", fileDescriptor_71599ad742c5de64) }

var fileDescriptor_71599ad742c5de64 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x4d, 0x4f, 0xf2, 0x40,
	0x10, 0xc7, 0xdb, 0xf2, 0xf0, 0x28, 0x03, 0x31, 0x30, 0x2d, 0xb1, 0xe9, 0x89, 0xcc, 0x89, 0x18,
	0xb3, 0x24, 0xe8, 0x89, 0xc4, 0x83, 0x42, 0x62, 0x3c, 0x70, 0xb0, 0x9e, 0x3c, 0x56, 0x19, 0x0d,
	0x11, 0x5a, 0xec, 0x2e, 0xfa, 0xc5, 0xfd, 0x00, 0xa6, 0x4b, 0x5b, 0x5b, 0x5a, 0xc2, 0x6d, 0x76,
	0x5e, 0xff, 0xf9, 0xcd, 0x2c, 0x9c, 0xaf, 0xa3, 0xaf, 0x25, 0x8f, 0x36, 0x71, 0xa4, 0xa2, 0x91,
	0xb6, 0x85, 0xb6, 0xe9, 0x12, 0xba, 0x3e, 0x07, 0x8b, 0x79, 0xe2, 0xf2, 0xf9, 0x73, 0xcb, 0x52,
	0xa1, 0x0b, 0x27, 0x3a, 0xe5, 0x61, 0xe6, 0x9a, 0x03, 0x73, 0xd8, 0xf2, 0xb3, 0x27, 0x3d, 0x42,
	0xaf, 0x90, 0x2d, 0x37, 0x51, 0x28, 0x59, 0xa7, 0xb3, 0x94, 0xc1, 0x3b, 0xe7, 0xe9, 0xbb, 0x27,
	0x12, 0x34, 0x75, 0xa5, 0x6b, 0x0d, 0xcc, 0x61, 0x7b, 0xdc, 0x11, 0xba, 0xf0, 0x49, 0xc5, 0xdb,
	0x57, 0xe5, 0xef, 0x42, 0x34, 0x01, 0x9c, 0xc6, 0x1c, 0x28, 0x2e, 0x49, 0x40, 0xf8, 0x17, 0x06,
	0xeb, 0xac, 0xa1, 0xb6, 0xb1, 0x0b, 0x8d, 0x37, 0xf9, 0xa1, 0x7b, 0x35, 0xfd, 0xc4, 0xa4, 0x67,
	0xb0, 0x4b, 0xb5, 0x47, 0x05, 0x0d, 0xe1, 0x34, 0xe4, 0xef, 0xf9, 0x41, 0x4d, 0x79, 0x94, 0x04,
	0xe0, 0x8c, 0x57, 0xbc, 0x27, 0xeb, 0x30, 0x99, 0x11, 0xd8, 0xa5, 0xfc, 0x63, 0x52, 0xa8, 0x0f,
	0xf6, 0x3d, 0xab, 0xdb, 0xd5, 0x4a, 0x17, 0xc8, 0x74, 0x02, 0xdd, 0x81, 0x53, 0x76, 0xa7, 0x8d,
	0x2e, 0xa0, 0x15, 0x64, 0x4e, 0xd7, 0x1c, 0x34, 0x2a, 0xd2, 0xff, 0xc2, 0x34, 0x85, 0x76, 0x21,
	0x82, 0x67, 0x60, 0x2d, 0x17, 0xe9, 0x78, 0x6b, 0xb9, 0xc8, 0xd9, 0x5a, 0x55, 0xb6, 0x8d, 0x9c,
	0xed, 0xf8, 0xc7, 0x84, 0xa6, 0xee, 0x82, 0x13, 0x68, 0x17, 0x28, 0xa3, 0x2d, 0xaa, 0xfb, 0xf2,
	0x1c, 0x51, 0xb3, 0x08, 0x32, 0xf0, 0x1a, 0x5a, 0xf9, 0xc1, 0x60, 0x4f, 0xec, 0x9f, 0x9a, 0x87,
	0xa2, 0x72, 0x4f, 0x64, 0x24, 0x13, 0x0b, 0x30, 0xd1, 0x16, 0xd5, 0x55, 0x78, 0x8e, 0xa8, 0xe1,
	0x4d, 0x06, 0xde, 0x40, 0xa7, 0x08, 0x10, 0x1d, 0x51, 0x83, 0xd9, 0xeb, 0x8b, 0x3a, 0xca, 0x64,
	0xbc, 0xfc, 0xd7, 0xdf, 0xe2, 0xea, 0x37, 0x00, 0x00, 0xff, 0xff, 0x16, 0x33, 0x24, 0x2c, 0x31,
	0x03, 0x00, 0x00,
}
