// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reservation/proto/reservation.proto

package reservation

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateReservationRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ShowingID            string   `protobuf:"bytes,2,opt,name=showingID,proto3" json:"showingID,omitempty"`
	SeatCount            int32    `protobuf:"varint,3,opt,name=seatCount,proto3" json:"seatCount,omitempty"`
	DoReservation        bool     `protobuf:"varint,4,opt,name=doReservation,proto3" json:"doReservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReservationRequest) Reset()         { *m = CreateReservationRequest{} }
func (m *CreateReservationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReservationRequest) ProtoMessage()    {}
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{0}
}

func (m *CreateReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReservationRequest.Unmarshal(m, b)
}
func (m *CreateReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReservationRequest.Marshal(b, m, deterministic)
}
func (m *CreateReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReservationRequest.Merge(m, src)
}
func (m *CreateReservationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReservationRequest.Size(m)
}
func (m *CreateReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReservationRequest proto.InternalMessageInfo

func (m *CreateReservationRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateReservationRequest) GetShowingID() string {
	if m != nil {
		return m.ShowingID
	}
	return ""
}

func (m *CreateReservationRequest) GetSeatCount() int32 {
	if m != nil {
		return m.SeatCount
	}
	return 0
}

func (m *CreateReservationRequest) GetDoReservation() bool {
	if m != nil {
		return m.DoReservation
	}
	return false
}

type CreateReservationResponse struct {
	Message              string             `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedReservation   *ReservationStruct `protobuf:"bytes,2,opt,name=createdReservation,proto3" json:"createdReservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateReservationResponse) Reset()         { *m = CreateReservationResponse{} }
func (m *CreateReservationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReservationResponse) ProtoMessage()    {}
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{1}
}

func (m *CreateReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReservationResponse.Unmarshal(m, b)
}
func (m *CreateReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReservationResponse.Marshal(b, m, deterministic)
}
func (m *CreateReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReservationResponse.Merge(m, src)
}
func (m *CreateReservationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateReservationResponse.Size(m)
}
func (m *CreateReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReservationResponse proto.InternalMessageInfo

func (m *CreateReservationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateReservationResponse) GetCreatedReservation() *ReservationStruct {
	if m != nil {
		return m.CreatedReservation
	}
	return nil
}

type InitReservationRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ShowingID            string   `protobuf:"bytes,2,opt,name=showingID,proto3" json:"showingID,omitempty"`
	SeatCount            int32    `protobuf:"varint,3,opt,name=seatCount,proto3" json:"seatCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitReservationRequest) Reset()         { *m = InitReservationRequest{} }
func (m *InitReservationRequest) String() string { return proto.CompactTextString(m) }
func (*InitReservationRequest) ProtoMessage()    {}
func (*InitReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{2}
}

func (m *InitReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitReservationRequest.Unmarshal(m, b)
}
func (m *InitReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitReservationRequest.Marshal(b, m, deterministic)
}
func (m *InitReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitReservationRequest.Merge(m, src)
}
func (m *InitReservationRequest) XXX_Size() int {
	return xxx_messageInfo_InitReservationRequest.Size(m)
}
func (m *InitReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitReservationRequest proto.InternalMessageInfo

func (m *InitReservationRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *InitReservationRequest) GetShowingID() string {
	if m != nil {
		return m.ShowingID
	}
	return ""
}

func (m *InitReservationRequest) GetSeatCount() int32 {
	if m != nil {
		return m.SeatCount
	}
	return 0
}

type InitReservationResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitReservationResponse) Reset()         { *m = InitReservationResponse{} }
func (m *InitReservationResponse) String() string { return proto.CompactTextString(m) }
func (*InitReservationResponse) ProtoMessage()    {}
func (*InitReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{3}
}

func (m *InitReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitReservationResponse.Unmarshal(m, b)
}
func (m *InitReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitReservationResponse.Marshal(b, m, deterministic)
}
func (m *InitReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitReservationResponse.Merge(m, src)
}
func (m *InitReservationResponse) XXX_Size() int {
	return xxx_messageInfo_InitReservationResponse.Size(m)
}
func (m *InitReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitReservationResponse proto.InternalMessageInfo

func (m *InitReservationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReadReservationRequest struct {
	ReservationID        string   `protobuf:"bytes,1,opt,name=reservationID,proto3" json:"reservationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReservationRequest) Reset()         { *m = ReadReservationRequest{} }
func (m *ReadReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ReadReservationRequest) ProtoMessage()    {}
func (*ReadReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{4}
}

func (m *ReadReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReservationRequest.Unmarshal(m, b)
}
func (m *ReadReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReservationRequest.Marshal(b, m, deterministic)
}
func (m *ReadReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReservationRequest.Merge(m, src)
}
func (m *ReadReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ReadReservationRequest.Size(m)
}
func (m *ReadReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReservationRequest proto.InternalMessageInfo

func (m *ReadReservationRequest) GetReservationID() string {
	if m != nil {
		return m.ReservationID
	}
	return ""
}

type ReadReservationResponse struct {
	Message              string             `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Reservation          *ReservationStruct `protobuf:"bytes,2,opt,name=reservation,proto3" json:"reservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReadReservationResponse) Reset()         { *m = ReadReservationResponse{} }
func (m *ReadReservationResponse) String() string { return proto.CompactTextString(m) }
func (*ReadReservationResponse) ProtoMessage()    {}
func (*ReadReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{5}
}

func (m *ReadReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReservationResponse.Unmarshal(m, b)
}
func (m *ReadReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReservationResponse.Marshal(b, m, deterministic)
}
func (m *ReadReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReservationResponse.Merge(m, src)
}
func (m *ReadReservationResponse) XXX_Size() int {
	return xxx_messageInfo_ReadReservationResponse.Size(m)
}
func (m *ReadReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReservationResponse proto.InternalMessageInfo

func (m *ReadReservationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReadReservationResponse) GetReservation() *ReservationStruct {
	if m != nil {
		return m.Reservation
	}
	return nil
}

type UpdateReservationRequest struct {
	ReservationID        string   `protobuf:"bytes,1,opt,name=reservationID,proto3" json:"reservationID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	SeatCount            int32    `protobuf:"varint,3,opt,name=seatCount,proto3" json:"seatCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReservationRequest) Reset()         { *m = UpdateReservationRequest{} }
func (m *UpdateReservationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateReservationRequest) ProtoMessage()    {}
func (*UpdateReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{6}
}

func (m *UpdateReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReservationRequest.Unmarshal(m, b)
}
func (m *UpdateReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReservationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReservationRequest.Merge(m, src)
}
func (m *UpdateReservationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateReservationRequest.Size(m)
}
func (m *UpdateReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReservationRequest proto.InternalMessageInfo

func (m *UpdateReservationRequest) GetReservationID() string {
	if m != nil {
		return m.ReservationID
	}
	return ""
}

func (m *UpdateReservationRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateReservationRequest) GetSeatCount() int32 {
	if m != nil {
		return m.SeatCount
	}
	return 0
}

type UpdateReservationResponse struct {
	UpdatedReservation   *ReservationStruct `protobuf:"bytes,1,opt,name=updatedReservation,proto3" json:"updatedReservation,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateReservationResponse) Reset()         { *m = UpdateReservationResponse{} }
func (m *UpdateReservationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateReservationResponse) ProtoMessage()    {}
func (*UpdateReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{7}
}

func (m *UpdateReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReservationResponse.Unmarshal(m, b)
}
func (m *UpdateReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReservationResponse.Marshal(b, m, deterministic)
}
func (m *UpdateReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReservationResponse.Merge(m, src)
}
func (m *UpdateReservationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateReservationResponse.Size(m)
}
func (m *UpdateReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReservationResponse proto.InternalMessageInfo

func (m *UpdateReservationResponse) GetUpdatedReservation() *ReservationStruct {
	if m != nil {
		return m.UpdatedReservation
	}
	return nil
}

func (m *UpdateReservationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteReservationRequest struct {
	ReservationID        string   `protobuf:"bytes,1,opt,name=reservationID,proto3" json:"reservationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReservationRequest) Reset()         { *m = DeleteReservationRequest{} }
func (m *DeleteReservationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationRequest) ProtoMessage()    {}
func (*DeleteReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{8}
}

func (m *DeleteReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationRequest.Unmarshal(m, b)
}
func (m *DeleteReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationRequest.Merge(m, src)
}
func (m *DeleteReservationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationRequest.Size(m)
}
func (m *DeleteReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationRequest proto.InternalMessageInfo

func (m *DeleteReservationRequest) GetReservationID() string {
	if m != nil {
		return m.ReservationID
	}
	return ""
}

type DeleteReservationResponse struct {
	Message              string             `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DeletedReservation   *ReservationStruct `protobuf:"bytes,2,opt,name=deletedReservation,proto3" json:"deletedReservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DeleteReservationResponse) Reset()         { *m = DeleteReservationResponse{} }
func (m *DeleteReservationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationResponse) ProtoMessage()    {}
func (*DeleteReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{9}
}

func (m *DeleteReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationResponse.Unmarshal(m, b)
}
func (m *DeleteReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationResponse.Marshal(b, m, deterministic)
}
func (m *DeleteReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationResponse.Merge(m, src)
}
func (m *DeleteReservationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationResponse.Size(m)
}
func (m *DeleteReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationResponse proto.InternalMessageInfo

func (m *DeleteReservationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeleteReservationResponse) GetDeletedReservation() *ReservationStruct {
	if m != nil {
		return m.DeletedReservation
	}
	return nil
}

type ReservationStruct struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ShowingID            string   `protobuf:"bytes,2,opt,name=showingID,proto3" json:"showingID,omitempty"`
	ReservationID        string   `protobuf:"bytes,3,opt,name=reservationID,proto3" json:"reservationID,omitempty"`
	SeatCount            int32    `protobuf:"varint,4,opt,name=seatCount,proto3" json:"seatCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationStruct) Reset()         { *m = ReservationStruct{} }
func (m *ReservationStruct) String() string { return proto.CompactTextString(m) }
func (*ReservationStruct) ProtoMessage()    {}
func (*ReservationStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{10}
}

func (m *ReservationStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationStruct.Unmarshal(m, b)
}
func (m *ReservationStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationStruct.Marshal(b, m, deterministic)
}
func (m *ReservationStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationStruct.Merge(m, src)
}
func (m *ReservationStruct) XXX_Size() int {
	return xxx_messageInfo_ReservationStruct.Size(m)
}
func (m *ReservationStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationStruct.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationStruct proto.InternalMessageInfo

func (m *ReservationStruct) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ReservationStruct) GetShowingID() string {
	if m != nil {
		return m.ShowingID
	}
	return ""
}

func (m *ReservationStruct) GetReservationID() string {
	if m != nil {
		return m.ReservationID
	}
	return ""
}

func (m *ReservationStruct) GetSeatCount() int32 {
	if m != nil {
		return m.SeatCount
	}
	return 0
}

type UpdateSeatCount struct {
	SeatCount            int32    `protobuf:"varint,1,opt,name=seatCount,proto3" json:"seatCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSeatCount) Reset()         { *m = UpdateSeatCount{} }
func (m *UpdateSeatCount) String() string { return proto.CompactTextString(m) }
func (*UpdateSeatCount) ProtoMessage()    {}
func (*UpdateSeatCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{11}
}

func (m *UpdateSeatCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSeatCount.Unmarshal(m, b)
}
func (m *UpdateSeatCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSeatCount.Marshal(b, m, deterministic)
}
func (m *UpdateSeatCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSeatCount.Merge(m, src)
}
func (m *UpdateSeatCount) XXX_Size() int {
	return xxx_messageInfo_UpdateSeatCount.Size(m)
}
func (m *UpdateSeatCount) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSeatCount.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSeatCount proto.InternalMessageInfo

func (m *UpdateSeatCount) GetSeatCount() int32 {
	if m != nil {
		return m.SeatCount
	}
	return 0
}

type GetReservationForUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReservationForUserRequest) Reset()         { *m = GetReservationForUserRequest{} }
func (m *GetReservationForUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetReservationForUserRequest) ProtoMessage()    {}
func (*GetReservationForUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{12}
}

func (m *GetReservationForUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReservationForUserRequest.Unmarshal(m, b)
}
func (m *GetReservationForUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReservationForUserRequest.Marshal(b, m, deterministic)
}
func (m *GetReservationForUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReservationForUserRequest.Merge(m, src)
}
func (m *GetReservationForUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetReservationForUserRequest.Size(m)
}
func (m *GetReservationForUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReservationForUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReservationForUserRequest proto.InternalMessageInfo

func (m *GetReservationForUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetReservationForUserResponse struct {
	AllReservations      []*ReservationStruct `protobuf:"bytes,1,rep,name=allReservations,proto3" json:"allReservations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetReservationForUserResponse) Reset()         { *m = GetReservationForUserResponse{} }
func (m *GetReservationForUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetReservationForUserResponse) ProtoMessage()    {}
func (*GetReservationForUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{13}
}

func (m *GetReservationForUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReservationForUserResponse.Unmarshal(m, b)
}
func (m *GetReservationForUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReservationForUserResponse.Marshal(b, m, deterministic)
}
func (m *GetReservationForUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReservationForUserResponse.Merge(m, src)
}
func (m *GetReservationForUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetReservationForUserResponse.Size(m)
}
func (m *GetReservationForUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReservationForUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReservationForUserResponse proto.InternalMessageInfo

func (m *GetReservationForUserResponse) GetAllReservations() []*ReservationStruct {
	if m != nil {
		return m.AllReservations
	}
	return nil
}

type DeleteReservationsForShowingRequest struct {
	ShowingID            string   `protobuf:"bytes,1,opt,name=showingID,proto3" json:"showingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReservationsForShowingRequest) Reset()         { *m = DeleteReservationsForShowingRequest{} }
func (m *DeleteReservationsForShowingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationsForShowingRequest) ProtoMessage()    {}
func (*DeleteReservationsForShowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{14}
}

func (m *DeleteReservationsForShowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationsForShowingRequest.Unmarshal(m, b)
}
func (m *DeleteReservationsForShowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationsForShowingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReservationsForShowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationsForShowingRequest.Merge(m, src)
}
func (m *DeleteReservationsForShowingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationsForShowingRequest.Size(m)
}
func (m *DeleteReservationsForShowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationsForShowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationsForShowingRequest proto.InternalMessageInfo

func (m *DeleteReservationsForShowingRequest) GetShowingID() string {
	if m != nil {
		return m.ShowingID
	}
	return ""
}

type DeleteReservationsForShowingResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReservationsForShowingResponse) Reset()         { *m = DeleteReservationsForShowingResponse{} }
func (m *DeleteReservationsForShowingResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationsForShowingResponse) ProtoMessage()    {}
func (*DeleteReservationsForShowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3f74d4833b9c82, []int{15}
}

func (m *DeleteReservationsForShowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationsForShowingResponse.Unmarshal(m, b)
}
func (m *DeleteReservationsForShowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationsForShowingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteReservationsForShowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationsForShowingResponse.Merge(m, src)
}
func (m *DeleteReservationsForShowingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationsForShowingResponse.Size(m)
}
func (m *DeleteReservationsForShowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationsForShowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationsForShowingResponse proto.InternalMessageInfo

func (m *DeleteReservationsForShowingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateReservationRequest)(nil), "CreateReservationRequest")
	proto.RegisterType((*CreateReservationResponse)(nil), "CreateReservationResponse")
	proto.RegisterType((*InitReservationRequest)(nil), "InitReservationRequest")
	proto.RegisterType((*InitReservationResponse)(nil), "InitReservationResponse")
	proto.RegisterType((*ReadReservationRequest)(nil), "ReadReservationRequest")
	proto.RegisterType((*ReadReservationResponse)(nil), "ReadReservationResponse")
	proto.RegisterType((*UpdateReservationRequest)(nil), "UpdateReservationRequest")
	proto.RegisterType((*UpdateReservationResponse)(nil), "UpdateReservationResponse")
	proto.RegisterType((*DeleteReservationRequest)(nil), "DeleteReservationRequest")
	proto.RegisterType((*DeleteReservationResponse)(nil), "DeleteReservationResponse")
	proto.RegisterType((*ReservationStruct)(nil), "ReservationStruct")
	proto.RegisterType((*UpdateSeatCount)(nil), "UpdateSeatCount")
	proto.RegisterType((*GetReservationForUserRequest)(nil), "GetReservationForUserRequest")
	proto.RegisterType((*GetReservationForUserResponse)(nil), "GetReservationForUserResponse")
	proto.RegisterType((*DeleteReservationsForShowingRequest)(nil), "DeleteReservationsForShowingRequest")
	proto.RegisterType((*DeleteReservationsForShowingResponse)(nil), "DeleteReservationsForShowingResponse")
}

func init() {
	proto.RegisterFile("reservation/proto/reservation.proto", fileDescriptor_5f3f74d4833b9c82)
}

var fileDescriptor_5f3f74d4833b9c82 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x41, 0x6f, 0xda, 0x30,
	0x14, 0x8e, 0x81, 0x75, 0xeb, 0x43, 0x15, 0xaa, 0x0f, 0xe0, 0x58, 0x74, 0x42, 0x2e, 0x93, 0x38,
	0x19, 0xa9, 0x9d, 0x76, 0x9a, 0xa6, 0xaa, 0x20, 0x26, 0xa4, 0x9d, 0x82, 0x7a, 0xd8, 0x61, 0x87,
	0xac, 0xb1, 0x3a, 0x24, 0x9a, 0x30, 0x3b, 0xe9, 0xd4, 0x1f, 0xb1, 0xdb, 0xfe, 0xd8, 0xfe, 0xd1,
	0x44, 0x48, 0x8b, 0x13, 0xdb, 0x10, 0xf5, 0xb0, 0x63, 0x9e, 0xdf, 0xb3, 0xbf, 0xf7, 0xbd, 0xef,
	0x7d, 0x00, 0xe7, 0x52, 0x28, 0x21, 0x1f, 0xc2, 0x74, 0x99, 0xc4, 0xe3, 0xb5, 0x4c, 0xd2, 0x64,
	0xac, 0x45, 0x78, 0x1e, 0x61, 0x7f, 0x10, 0x90, 0x89, 0x14, 0x61, 0x2a, 0x82, 0xdd, 0x59, 0x20,
	0x7e, 0x66, 0x42, 0xa5, 0xb8, 0x0b, 0x47, 0x99, 0x12, 0x72, 0x3e, 0x25, 0x68, 0x80, 0x46, 0xc7,
	0x41, 0xf1, 0x85, 0xfb, 0x70, 0xac, 0x7e, 0x24, 0xbf, 0x96, 0xf1, 0xdd, 0x7c, 0x4a, 0x1a, 0xf9,
	0xd1, 0x2e, 0x90, 0x9f, 0x8a, 0x30, 0x9d, 0x24, 0x59, 0x9c, 0x92, 0xe6, 0x00, 0x8d, 0x5e, 0x05,
	0xbb, 0x00, 0x1e, 0xc2, 0x49, 0x94, 0x68, 0x6f, 0x91, 0xd6, 0x00, 0x8d, 0xde, 0x04, 0xe5, 0x20,
	0x7b, 0x04, 0xdf, 0x82, 0x4a, 0xad, 0x93, 0x58, 0x09, 0x4c, 0xe0, 0xf5, 0xbd, 0x50, 0x2a, 0xbc,
	0x13, 0x05, 0xae, 0xa7, 0x4f, 0x7c, 0x0d, 0xf8, 0x36, 0x2f, 0x8b, 0xf4, 0x17, 0x36, 0x08, 0xdb,
	0x17, 0x98, 0x6b, 0xb1, 0x45, 0x2a, 0xb3, 0xdb, 0x34, 0xb0, 0x64, 0xb3, 0x15, 0x74, 0xe7, 0xf1,
	0x32, 0xfd, 0x3f, 0x74, 0xb0, 0x4b, 0xe8, 0x19, 0xaf, 0x1d, 0x6a, 0x93, 0x7d, 0x82, 0x6e, 0x20,
	0xc2, 0xc8, 0x02, 0x71, 0x08, 0x27, 0xda, 0x8c, 0x9f, 0x91, 0x96, 0x83, 0x6c, 0x09, 0x3d, 0xa3,
	0xfe, 0x20, 0xb7, 0xef, 0xa1, 0x2d, 0x6b, 0x91, 0xaa, 0xa7, 0xb1, 0x07, 0x20, 0x37, 0xeb, 0xc8,
	0x2e, 0xaf, 0x5a, 0x60, 0x35, 0xd6, 0x1b, 0x06, 0xeb, 0x6e, 0x5e, 0x1f, 0xc1, 0xb7, 0xbc, 0x5b,
	0x34, 0x79, 0x0d, 0x38, 0xcb, 0x0f, 0x4b, 0x32, 0x41, 0x6e, 0x99, 0x98, 0xd9, 0x3a, 0x51, 0x8d,
	0xf2, 0x74, 0xae, 0x80, 0x4c, 0xc5, 0x4a, 0xbc, 0xbc, 0xe5, 0x0d, 0x78, 0xcb, 0x0d, 0x75, 0xd4,
	0x1f, 0xe5, 0x65, 0x75, 0xd5, 0x6f, 0x66, 0xb3, 0xdf, 0x08, 0x4e, 0x8d, 0xcc, 0x17, 0x2a, 0xdf,
	0x68, 0xb6, 0x69, 0x9b, 0x6f, 0x69, 0x8e, 0xad, 0xea, 0x1c, 0xc7, 0xd0, 0xd9, 0xce, 0x71, 0xf1,
	0xec, 0x20, 0xa5, 0x02, 0x54, 0x2d, 0xf8, 0x00, 0xfd, 0xcf, 0x42, 0xdf, 0xa7, 0x59, 0x22, 0x6f,
	0x94, 0x90, 0x07, 0x96, 0x98, 0x7d, 0x83, 0x33, 0x47, 0x5d, 0xc1, 0xfb, 0x47, 0xe8, 0x84, 0xab,
	0x95, 0x96, 0xa0, 0x08, 0x1a, 0x34, 0x1d, 0xd4, 0x56, 0x53, 0xd9, 0x04, 0xce, 0x8d, 0x91, 0xaa,
	0x59, 0x22, 0x17, 0x5b, 0xb6, 0x9e, 0xd0, 0x95, 0x08, 0x45, 0x15, 0x42, 0xd9, 0x15, 0x0c, 0xf7,
	0x5f, 0x72, 0x48, 0x22, 0x17, 0x7f, 0x5b, 0xd0, 0xd6, 0x55, 0x3c, 0x83, 0x4e, 0xc5, 0x7e, 0x70,
	0x8f, 0xdb, 0xed, 0x8f, 0x12, 0xee, 0x70, 0x2a, 0xe6, 0xe1, 0x2f, 0x70, 0x6a, 0xf8, 0x35, 0xf6,
	0xb9, 0xeb, 0x97, 0x85, 0x52, 0xee, 0xb4, 0x77, 0xe6, 0x6d, 0x50, 0x55, 0xfc, 0x09, 0xf7, 0xb8,
	0xdd, 0xf1, 0x28, 0xe1, 0x0e, 0x2b, 0xdb, 0xa2, 0x32, 0x4c, 0x00, 0xfb, 0xdc, 0x65, 0x48, 0x94,
	0x72, 0xa7, 0x67, 0x6c, 0x6f, 0x33, 0xd8, 0xc7, 0x3e, 0x77, 0xed, 0x3a, 0xa5, 0xdc, 0xb9, 0xc4,
	0xcc, 0xc3, 0x5f, 0xa1, 0x5b, 0xd6, 0x9b, 0x2a, 0x04, 0x87, 0xcf, 0xf8, 0x3e, 0x01, 0xd3, 0xb7,
	0x7c, 0xaf, 0x4e, 0x99, 0x87, 0xef, 0xa1, 0xbf, 0x4f, 0x26, 0x78, 0xc8, 0x6b, 0x48, 0x91, 0xbe,
	0xe3, 0x75, 0xb4, 0xc6, 0xbc, 0xef, 0x47, 0xf9, 0x3f, 0x89, 0xcb, 0x7f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x55, 0xca, 0x66, 0x3b, 0x70, 0x08, 0x00, 0x00,
}
