// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/proto/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ac6eb5dc4a0e42f, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type CreateUserResponse struct {
	Message              string      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NewUser              *UserStruct `protobuf:"bytes,2,opt,name=newUser,proto3" json:"newUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ac6eb5dc4a0e42f, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateUserResponse) GetNewUser() *UserStruct {
	if m != nil {
		return m.NewUser
	}
	return nil
}

type DeleteUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ac6eb5dc4a0e42f, []int{2}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type DeleteUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ac6eb5dc4a0e42f, []int{3}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ShowAllUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowAllUserRequest) Reset()         { *m = ShowAllUserRequest{} }
func (m *ShowAllUserRequest) String() string { return proto.CompactTextString(m) }
func (*ShowAllUserRequest) ProtoMessage()    {}
func (*ShowAllUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ac6eb5dc4a0e42f, []int{4}
}

func (m *ShowAllUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowAllUserRequest.Unmarshal(m, b)
}
func (m *ShowAllUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowAllUserRequest.Marshal(b, m, deterministic)
}
func (m *ShowAllUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowAllUserRequest.Merge(m, src)
}
func (m *ShowAllUserRequest) XXX_Size() int {
	return xxx_messageInfo_ShowAllUserRequest.Size(m)
}
func (m *ShowAllUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowAllUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowAllUserRequest proto.InternalMessageInfo

type ShowAllUserResponse struct {
	AllUsers             []*UserStruct `protobuf:"bytes,1,rep,name=allUsers,proto3" json:"allUsers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ShowAllUserResponse) Reset()         { *m = ShowAllUserResponse{} }
func (m *ShowAllUserResponse) String() string { return proto.CompactTextString(m) }
func (*ShowAllUserResponse) ProtoMessage()    {}
func (*ShowAllUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ac6eb5dc4a0e42f, []int{5}
}

func (m *ShowAllUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowAllUserResponse.Unmarshal(m, b)
}
func (m *ShowAllUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowAllUserResponse.Marshal(b, m, deterministic)
}
func (m *ShowAllUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowAllUserResponse.Merge(m, src)
}
func (m *ShowAllUserResponse) XXX_Size() int {
	return xxx_messageInfo_ShowAllUserResponse.Size(m)
}
func (m *ShowAllUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowAllUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowAllUserResponse proto.InternalMessageInfo

func (m *ShowAllUserResponse) GetAllUsers() []*UserStruct {
	if m != nil {
		return m.AllUsers
	}
	return nil
}

type ReadUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ac6eb5dc4a0e42f, []int{6}
}

func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(m, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

func (m *ReadUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type ReadUserResponse struct {
	Message              string      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *UserStruct `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ac6eb5dc4a0e42f, []int{7}
}

func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(m, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReadUserResponse) GetUser() *UserStruct {
	if m != nil {
		return m.User
	}
	return nil
}

type UserStruct struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	UserID               string   `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStruct) Reset()         { *m = UserStruct{} }
func (m *UserStruct) String() string { return proto.CompactTextString(m) }
func (*UserStruct) ProtoMessage()    {}
func (*UserStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ac6eb5dc4a0e42f, []int{8}
}

func (m *UserStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStruct.Unmarshal(m, b)
}
func (m *UserStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStruct.Marshal(b, m, deterministic)
}
func (m *UserStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStruct.Merge(m, src)
}
func (m *UserStruct) XXX_Size() int {
	return xxx_messageInfo_UserStruct.Size(m)
}
func (m *UserStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStruct.DiscardUnknown(m)
}

var xxx_messageInfo_UserStruct proto.InternalMessageInfo

func (m *UserStruct) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserStruct) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserStruct) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserStruct) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "CreateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "DeleteUserResponse")
	proto.RegisterType((*ShowAllUserRequest)(nil), "ShowAllUserRequest")
	proto.RegisterType((*ShowAllUserResponse)(nil), "ShowAllUserResponse")
	proto.RegisterType((*ReadUserRequest)(nil), "ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "ReadUserResponse")
	proto.RegisterType((*UserStruct)(nil), "UserStruct")
}

func init() { proto.RegisterFile("user/proto/user.proto", fileDescriptor_3ac6eb5dc4a0e42f) }

var fileDescriptor_3ac6eb5dc4a0e42f = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x13, 0x5b, 0xfb, 0xe7, 0xf5, 0x60, 0x3b, 0xa9, 0x12, 0x82, 0x60, 0x59, 0x10, 0x2b,
	0xc2, 0x16, 0xeb, 0x41, 0xf0, 0x20, 0x88, 0xbd, 0x78, 0xd0, 0x43, 0x4a, 0xcf, 0x12, 0x75, 0xfc,
	0x03, 0x69, 0x53, 0xb3, 0x09, 0xfd, 0xc8, 0x7e, 0x0d, 0xd9, 0x34, 0x6d, 0xd2, 0x44, 0xa9, 0x07,
	0x6f, 0x3b, 0xf3, 0x26, 0x6f, 0x67, 0xe6, 0xb7, 0xc1, 0x7e, 0xac, 0x38, 0x1c, 0xcc, 0xc3, 0x20,
	0x0a, 0x06, 0xfa, 0x28, 0x93, 0xa3, 0x78, 0x44, 0xe7, 0x36, 0x64, 0x2f, 0xe2, 0x89, 0xe2, 0xd0,
	0xe5, 0xcf, 0x98, 0x55, 0x44, 0x87, 0x68, 0xbe, 0x7e, 0x84, 0x2a, 0x7a, 0xf0, 0xa6, 0x6c, 0x9b,
	0x3d, 0xb3, 0xdf, 0x74, 0xb3, 0x04, 0x39, 0x68, 0xf8, 0x5e, 0x2a, 0xee, 0x24, 0xe2, 0x3a, 0xa6,
	0x36, 0x2a, 0xde, 0x1b, 0xdb, 0x95, 0x9e, 0xd9, 0xdf, 0x75, 0xf5, 0x51, 0x4c, 0x40, 0xf9, 0x0b,
	0xd4, 0x3c, 0x98, 0x29, 0x26, 0x1b, 0xf5, 0x29, 0x2b, 0xa5, 0x6b, 0x97, 0xfe, 0xab, 0x90, 0x8e,
	0x51, 0x9f, 0xf1, 0x42, 0x17, 0x27, 0xe6, 0xad, 0x61, 0x4b, 0xea, 0x60, 0x1c, 0x85, 0xf1, 0x73,
	0xe4, 0xae, 0x34, 0x71, 0x86, 0xce, 0x88, 0x7d, 0xde, 0xec, 0xfb, 0x00, 0x35, 0x3d, 0xda, 0xdd,
	0x28, 0x35, 0x4d, 0x23, 0x21, 0x41, 0xf9, 0xe2, 0x6d, 0x3d, 0x88, 0x2e, 0x68, 0xfc, 0x1e, 0x2c,
	0x6e, 0x7c, 0x3f, 0xe7, 0x2e, 0xae, 0x61, 0x6d, 0x64, 0x53, 0x9b, 0x13, 0x34, 0xbc, 0x65, 0x4a,
	0xd9, 0x66, 0xaf, 0x52, 0xec, 0x78, 0x2d, 0x8a, 0x53, 0xec, 0xb9, 0xec, 0xbd, 0xfc, 0xa5, 0xe1,
	0x7b, 0xb4, 0xb3, 0xd2, 0xad, 0x2b, 0x3b, 0x42, 0x35, 0xfe, 0x65, 0x5f, 0x89, 0x20, 0xe6, 0x40,
	0x96, 0xfb, 0x4f, 0xba, 0xb9, 0x01, 0xaa, 0xf9, 0x01, 0x86, 0x5f, 0x26, 0xaa, 0xfa, 0x4a, 0xba,
	0x04, 0x32, 0xfc, 0x44, 0xb2, 0xf4, 0xd8, 0x1c, 0x4b, 0x96, 0xdf, 0x87, 0x30, 0xf4, 0x87, 0x19,
	0x33, 0x22, 0x59, 0xa2, 0xed, 0x58, 0xb2, 0x0c, 0x55, 0x18, 0x74, 0x85, 0x56, 0x0e, 0x13, 0x59,
	0xb2, 0x8c, 0xd2, 0xe9, 0xca, 0x1f, 0x48, 0x0a, 0x83, 0xce, 0xd1, 0x58, 0xed, 0x9d, 0xda, 0xb2,
	0x40, 0xcb, 0xe9, 0xc8, 0x22, 0x14, 0x61, 0x3c, 0xd5, 0x92, 0xff, 0xe8, 0xe2, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0xd7, 0x2a, 0x1a, 0xba, 0x60, 0x03, 0x00, 0x00,
}
